import type {
  DifficultyLevel,
  ExpertiseLevel,
  OfficialRating,
  PlayStyle,
} from "@gamefinder/shared";

export type SeedGame = {
  title: string;
  slug: string;
  description: string;
  releaseYear: number;
  genres: string[];
  platforms: string[];
  minAgeRecommendation: number;
  officialRating: OfficialRating;
  difficultyLevel: DifficultyLevel;
  expertiseRequired: ExpertiseLevel;
  playStyles: PlayStyle[];
  averageSessionMinutes: number;
  contentNotes: string[];
  maxPlayers: number | null;
  playerCountLabel: string;
};

export const SEED_GAMES: SeedGame[] = [
  {
    title: "Left 4 Dead",
    slug: "left-4-dead",
    description:
      "Cooperative zombie survival shooter focused on team play through campaign episodes.",
    releaseYear: 2008,
    genres: ["shooter", "action"],
    platforms: ["pc", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["co-op", "online-multiplayer"],
    averageSessionMinutes: 45,
    contentNotes: ["violence", "horror", "online-interactions"],
    maxPlayers: 4,
    playerCountLabel: "1-4 co-op",
  },
  {
    title: "Left 4 Dead 2",
    slug: "left-4-dead-2",
    description:
      "Expanded cooperative zombie shooter with new campaigns, weapons, and special infected.",
    releaseYear: 2009,
    genres: ["shooter", "action"],
    platforms: ["pc", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "challenging",
    expertiseRequired: "intermediate",
    playStyles: ["co-op", "online-multiplayer"],
    averageSessionMinutes: 50,
    contentNotes: ["violence", "horror", "online-interactions"],
    maxPlayers: 4,
    playerCountLabel: "1-4 co-op",
  },
  {
    title: "Prototype",
    slug: "prototype",
    description:
      "Open-world action game with shape-shifting powers and fast traversal in a infected city.",
    releaseYear: 2009,
    genres: ["action", "adventure"],
    platforms: ["pc", "playstation", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "story-driven", "sandbox"],
    averageSessionMinutes: 60,
    contentNotes: ["violence", "language"],
    maxPlayers: 1,
    playerCountLabel: "Single player",
  },
  {
    title: "Prototype 2",
    slug: "prototype-2",
    description:
      "Sequel action game continuing open-world powers, combat, and viral outbreak themes.",
    releaseYear: 2012,
    genres: ["action", "adventure"],
    platforms: ["pc", "playstation", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "story-driven", "sandbox"],
    averageSessionMinutes: 60,
    contentNotes: ["violence", "language"],
    maxPlayers: 1,
    playerCountLabel: "Single player",
  },
  {
    title: "Call of Duty: Modern Warfare",
    slug: "call-of-duty-modern-warfare",
    description:
      "Military first-person shooter with cinematic campaign and competitive multiplayer modes.",
    releaseYear: 2019,
    genres: ["shooter", "action"],
    platforms: ["pc", "playstation", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "challenging",
    expertiseRequired: "advanced",
    playStyles: ["solo", "competitive", "online-multiplayer", "story-driven"],
    averageSessionMinutes: 40,
    contentNotes: ["violence", "language", "online-interactions"],
    maxPlayers: null,
    playerCountLabel: "Online multiplayer",
  },
  {
    title: "Call of Duty: Black Ops",
    slug: "call-of-duty-black-ops",
    description:
      "Campaign-driven military shooter with arcade-style multiplayer and co-op options.",
    releaseYear: 2010,
    genres: ["shooter", "action"],
    platforms: ["pc", "playstation", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "competitive", "online-multiplayer", "co-op"],
    averageSessionMinutes: 35,
    contentNotes: ["violence", "language", "online-interactions"],
    maxPlayers: null,
    playerCountLabel: "Online multiplayer",
  },
  {
    title: "Call of Duty: Warzone",
    slug: "call-of-duty-warzone",
    description:
      "Free-to-play battle royale shooter with squad-based matches and loadout progression.",
    releaseYear: 2020,
    genres: ["shooter", "battle-royale"],
    platforms: ["pc", "playstation", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "hardcore",
    expertiseRequired: "expert",
    playStyles: ["competitive", "online-multiplayer", "co-op"],
    averageSessionMinutes: 30,
    contentNotes: ["violence", "language", "online-interactions"],
    maxPlayers: null,
    playerCountLabel: "Squads online",
  },
  {
    title: "Halo 3",
    slug: "halo-3",
    description:
      "Sci-fi shooter with story campaign, iconic multiplayer, and cooperative modes.",
    releaseYear: 2007,
    genres: ["shooter", "action"],
    platforms: ["xbox", "pc"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "co-op", "competitive", "online-multiplayer", "story-driven"],
    averageSessionMinutes: 45,
    contentNotes: ["violence", "online-interactions"],
    maxPlayers: 4,
    playerCountLabel: "1-4 campaign co-op",
  },
  {
    title: "Halo: Reach",
    slug: "halo-reach",
    description:
      "Prequel sci-fi shooter emphasizing squad campaign play and large-scale multiplayer.",
    releaseYear: 2010,
    genres: ["shooter", "action"],
    platforms: ["xbox", "pc"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "co-op", "competitive", "online-multiplayer", "story-driven"],
    averageSessionMinutes: 45,
    contentNotes: ["violence", "online-interactions"],
    maxPlayers: 4,
    playerCountLabel: "1-4 campaign co-op",
  },
  {
    title: "Minecraft",
    slug: "minecraft",
    description:
      "Sandbox building and survival game with creative and survival modes across platforms.",
    releaseYear: 2011,
    genres: ["sandbox", "survival"],
    platforms: ["pc", "playstation", "xbox", "switch", "mobile"],
    minAgeRecommendation: 7,
    officialRating: "E10",
    difficultyLevel: "casual",
    expertiseRequired: "beginner",
    playStyles: ["solo", "co-op", "online-multiplayer", "sandbox"],
    averageSessionMinutes: 60,
    contentNotes: ["online-interactions"],
    maxPlayers: null,
    playerCountLabel: "1+ online",
  },
  {
    title: "Fortnite",
    slug: "fortnite",
    description:
      "Free-to-play battle royale and creative modes with building mechanics and live events.",
    releaseYear: 2017,
    genres: ["shooter", "battle-royale"],
    platforms: ["pc", "playstation", "xbox", "switch", "mobile"],
    minAgeRecommendation: 13,
    officialRating: "T",
    difficultyLevel: "challenging",
    expertiseRequired: "intermediate",
    playStyles: ["competitive", "online-multiplayer", "co-op", "sandbox"],
    averageSessionMinutes: 25,
    contentNotes: ["violence", "online-interactions"],
    maxPlayers: null,
    playerCountLabel: "Squads online",
  },
  {
    title: "The Legend of Zelda: Breath of the Wild",
    slug: "zelda-breath-of-the-wild",
    description:
      "Open-world action adventure with exploration, puzzles, and flexible play pacing.",
    releaseYear: 2017,
    genres: ["adventure", "action"],
    platforms: ["switch", "wii-u"],
    minAgeRecommendation: 10,
    officialRating: "E10",
    difficultyLevel: "moderate",
    expertiseRequired: "casual",
    playStyles: ["solo", "story-driven", "sandbox"],
    averageSessionMinutes: 90,
    contentNotes: ["fantasy-violence"],
    maxPlayers: 1,
    playerCountLabel: "Single player",
  },
  {
    title: "Super Mario Odyssey",
    slug: "super-mario-odyssey",
    description:
      "3D platform adventure with approachable mechanics and optional challenge areas.",
    releaseYear: 2017,
    genres: ["platformer", "adventure"],
    platforms: ["switch"],
    minAgeRecommendation: 7,
    officialRating: "E10",
    difficultyLevel: "casual",
    expertiseRequired: "beginner",
    playStyles: ["solo", "co-op", "story-driven"],
    averageSessionMinutes: 45,
    contentNotes: [],
    maxPlayers: 2,
    playerCountLabel: "1-2 local co-op",
  },
  {
    title: "Stardew Valley",
    slug: "stardew-valley",
    description:
      "Farming and life simulation with crafting, relationships, and relaxed progression.",
    releaseYear: 2016,
    genres: ["simulation", "rpg"],
    platforms: ["pc", "playstation", "xbox", "switch", "mobile"],
    minAgeRecommendation: 10,
    officialRating: "E10",
    difficultyLevel: "casual",
    expertiseRequired: "beginner",
    playStyles: ["solo", "co-op", "sandbox"],
    averageSessionMinutes: 75,
    contentNotes: [],
    maxPlayers: 4,
    playerCountLabel: "1-4 co-op",
  },
  {
    title: "Elden Ring",
    slug: "elden-ring",
    description:
      "Open-world action RPG known for demanding combat and deep build customization.",
    releaseYear: 2022,
    genres: ["rpg", "action"],
    platforms: ["pc", "playstation", "xbox"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "hardcore",
    expertiseRequired: "expert",
    playStyles: ["solo", "co-op", "online-multiplayer", "story-driven"],
    averageSessionMinutes: 120,
    contentNotes: ["violence", "fantasy-violence"],
    maxPlayers: 4,
    playerCountLabel: "1-4 co-op",
  },
  {
    title: "The Last of Us",
    slug: "the-last-of-us",
    description:
      "Story-driven survival action game focused on narrative, stealth, and resource tension.",
    releaseYear: 2013,
    genres: ["action", "adventure"],
    platforms: ["playstation", "pc"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "story-driven"],
    averageSessionMinutes: 90,
    contentNotes: ["violence", "language", "horror"],
    maxPlayers: 1,
    playerCountLabel: "Single player",
  },
  {
    title: "The Elder Scrolls V: Skyrim",
    slug: "skyrim",
    description:
      "Open-world fantasy RPG with exploration, quests, and flexible character builds.",
    releaseYear: 2011,
    genres: ["rpg", "adventure"],
    platforms: ["pc", "playstation", "xbox", "switch"],
    minAgeRecommendation: 17,
    officialRating: "M",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "story-driven", "sandbox"],
    averageSessionMinutes: 120,
    contentNotes: ["violence", "fantasy-violence"],
    maxPlayers: 1,
    playerCountLabel: "Single player",
  },
  {
    title: "Rocket League",
    slug: "rocket-league",
    description:
      "Arcade sports game combining cars and soccer-style matches in short competitive rounds.",
    releaseYear: 2015,
    genres: ["sports", "racing"],
    platforms: ["pc", "playstation", "xbox", "switch"],
    minAgeRecommendation: 3,
    officialRating: "E",
    difficultyLevel: "challenging",
    expertiseRequired: "advanced",
    playStyles: ["competitive", "online-multiplayer", "couch-co-op"],
    averageSessionMinutes: 10,
    contentNotes: ["online-interactions"],
    maxPlayers: 8,
    playerCountLabel: "1-8 online",
  },
  {
    title: "Portal 2",
    slug: "portal-2",
    description:
      "Puzzle platform game built around portal mechanics, humor, and cooperative test chambers.",
    releaseYear: 2011,
    genres: ["puzzle", "platformer"],
    platforms: ["pc", "playstation", "xbox"],
    minAgeRecommendation: 10,
    officialRating: "E10",
    difficultyLevel: "moderate",
    expertiseRequired: "intermediate",
    playStyles: ["solo", "co-op", "story-driven"],
    averageSessionMinutes: 60,
    contentNotes: ["fantasy-violence"],
    maxPlayers: 2,
    playerCountLabel: "1-2 co-op",
  },
  {
    title: "Among Us",
    slug: "among-us",
    description:
      "Social deduction party game where crewmates complete tasks while impostors sabotage.",
    releaseYear: 2018,
    genres: ["party", "strategy"],
    platforms: ["pc", "playstation", "xbox", "switch", "mobile"],
    minAgeRecommendation: 10,
    officialRating: "E10",
    difficultyLevel: "casual",
    expertiseRequired: "beginner",
    playStyles: ["online-multiplayer", "couch-co-op"],
    averageSessionMinutes: 15,
    contentNotes: ["online-interactions"],
    maxPlayers: 15,
    playerCountLabel: "4-15 online",
  },
];

export const SEED_GENRES = [
  { slug: "shooter", name: "Shooter" },
  { slug: "action", name: "Action" },
  { slug: "adventure", name: "Adventure" },
  { slug: "rpg", name: "RPG" },
  { slug: "platformer", name: "Platformer" },
  { slug: "sandbox", name: "Sandbox" },
  { slug: "survival", name: "Survival" },
  { slug: "simulation", name: "Simulation" },
  { slug: "sports", name: "Sports" },
  { slug: "racing", name: "Racing" },
  { slug: "puzzle", name: "Puzzle" },
  { slug: "party", name: "Party" },
  { slug: "strategy", name: "Strategy" },
  { slug: "battle-royale", name: "Battle Royale" },
];

export const SEED_PLATFORMS = [
  { slug: "pc", name: "PC" },
  { slug: "playstation", name: "PlayStation" },
  { slug: "xbox", name: "Xbox" },
  { slug: "switch", name: "Nintendo Switch" },
  { slug: "mobile", name: "Mobile" },
  { slug: "wii-u", name: "Wii U" },
];
